---
- hosts: iplist
  remote_user: root
  gather_facts: false
  tasks:
     - name: "拷贝主机上的文件到目标服务器上"
       copy:
           src: "{{ item.src }}"
           dest: "{{ item.dest }}"
           owner: root
           group: root
           mode: "{{ item.mode }}"
       with_items:
           - { src: "/root/.guozhichao/sshd_config", dest: "/etc/ssh/sshd_config", mode: "0600" }
       notify: sshd.service
  handlers:
       - name: sshd.service
         shell: systemctl restart sshd.service
