---
- name: create users
  hosts: 172.25.9.71
  tasks:
          - name: create users
            user:
                    name: "{{ item }}"
                    password: "{{ '123456' |password_hash('sha512') }}"
                    shell: /bin/bash
                    state: present
            loop:
                    - ops
